DROP TABLE JJY_BOARD CASCADE CONSTRAINTS;

CREATE TABLE JJY_BOARD (
    board_no  NUMBER(4) NOT NULL,
    mem_no NUMBER(4) NOT NULL,
    title VARCHAR2(100) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    create_date DATE DEFAULT SYSDATE NOT NULL,
    modify_date DATE DEFAULT SYSDATE NOT NULL,
    deleted_date DATE,
    
    CONSTRAINT FK_CODE FOREIGN KEY(mem_no) REFERENCES MEMBER(MEM_NO) ON DELETE SET NULL
);

COMMIT;